-- StatWeights.lua

local Weights = BetterGearScore.Weights

Weights.BASE_STATS = {
    "STRENGTH",
    "AGILITY",
    "INTELLECT",
    "STAMINA",
    "SPIRIT",
}

Weights.OTHER_STATS = {
    "ARMOR",
    "ATTACKPOWER",
    "RANGED_ATTACKPOWER",
    "SPELLPOWER",
    "HEALING",
    "DEFENSE",
    "DODGE",
    "PARRY",
    "BLOCK",
    "CRITICAL",
    "HIT",
    "HASTE",
    "MP5",
}

Weights.PROFILE_WEIGHTS = {
    WARRIOR_DPS = {
        STRENGTH = 1.0,
        AGILITY = 0.55,
        INTELLECT = 0.0,
        STAMINA = 0.40,
        SPIRIT = 0.0,
        ARMOR = 0.10,
        ATTACKPOWER = 0.90,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.10,
        PARRY = 0.10,
        BLOCK = 0.0,
        CRITICAL = 0.85,
        HIT = 1.0,
        HASTE = 0.85,
        MP5 = 0.0,
    },

    WARRIOR_TANK = {
        STRENGTH = 0.45,
        AGILITY = 0.45,
        INTELLECT = 0.0,
        STAMINA = 1.0,
        SPIRIT = 0.0,
        ARMOR = 0.85,
        ATTACKPOWER = 0.35,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 1.0,
        DODGE = 0.85,
        PARRY = 0.85,
        BLOCK = 0.75,
        CRITICAL = 0.20,
        HIT = 0.45,
        HASTE = 0.20,
        MP5 = 0.0,
    },

    PALADIN_DPS = {
        STRENGTH = 1.0,
        AGILITY = 0.35,
        INTELLECT = 0.35,
        STAMINA = 0.40,
        SPIRIT = 0.0,
        ARMOR = 0.10,
        ATTACKPOWER = 0.85,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.35,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.10,
        PARRY = 0.10,
        BLOCK = 0.10,
        CRITICAL = 0.80,
        HIT = 1.0,
        HASTE = 0.75,
        MP5 = 0.15,
    },

    PALADIN_TANK = {
        STRENGTH = 0.40,
        AGILITY = 0.20,
        INTELLECT = 0.55,
        STAMINA = 1.0,
        SPIRIT = 0.0,
        ARMOR = 0.85,
        ATTACKPOWER = 0.25,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.60,
        HEALING = 0.0,
        DEFENSE = 1.0,
        DODGE = 0.75,
        PARRY = 0.75,
        BLOCK = 0.85,
        CRITICAL = 0.20,
        HIT = 0.45,
        HASTE = 0.20,
        MP5 = 0.45,
    },

    PALADIN_HEALER = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 1.0,
        STAMINA = 0.45,
        SPIRIT = 0.45,
        ARMOR = 0.10,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.35,
        HEALING = 1.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.55,
        HIT = 0.0,
        HASTE = 0.65,
        MP5 = 0.90,
    },

    HUNTER_DPS = {
        STRENGTH = 0.0,
        AGILITY = 1.0,
        INTELLECT = 0.35,
        STAMINA = 0.35,
        SPIRIT = 0.0,
        ARMOR = 0.10,
        ATTACKPOWER = 0.75,
        RANGED_ATTACKPOWER = 1.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.20,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.85,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.25,
    },

    ROGUE_DPS = {
        STRENGTH = 0.55,
        AGILITY = 1.0,
        INTELLECT = 0.0,
        STAMINA = 0.35,
        SPIRIT = 0.0,
        ARMOR = 0.05,
        ATTACKPOWER = 0.90,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.20,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.85,
        HIT = 1.0,
        HASTE = 0.85,
        MP5 = 0.0,
    },

    PRIEST_HEALER = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 1.0,
        STAMINA = 0.45,
        SPIRIT = 0.85,
        ARMOR = 0.05,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.30,
        HEALING = 1.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.50,
        HIT = 0.0,
        HASTE = 0.65,
        MP5 = 0.80,
    },

    PRIEST_DPS = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 0.85,
        STAMINA = 0.45,
        SPIRIT = 0.45,
        ARMOR = 0.05,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 1.0,
        HEALING = 0.15,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.70,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.35,
    },

    SHAMAN_ELEMENTAL = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 0.85,
        STAMINA = 0.45,
        SPIRIT = 0.25,
        ARMOR = 0.10,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 1.0,
        HEALING = 0.15,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.75,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.35,
    },

    SHAMAN_ENHANCEMENT = {
        STRENGTH = 0.65,
        AGILITY = 0.75,
        INTELLECT = 0.35,
        STAMINA = 0.40,
        SPIRIT = 0.0,
        ARMOR = 0.15,
        ATTACKPOWER = 0.90,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.15,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.20,
        PARRY = 0.10,
        BLOCK = 0.15,
        CRITICAL = 0.80,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.20,
    },

    SHAMAN_HEALER = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 1.0,
        STAMINA = 0.45,
        SPIRIT = 0.35,
        ARMOR = 0.10,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.35,
        HEALING = 1.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.55,
        HIT = 0.0,
        HASTE = 0.65,
        MP5 = 0.95,
    },

    MAGE_DPS = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 0.85,
        STAMINA = 0.35,
        SPIRIT = 0.35,
        ARMOR = 0.05,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 1.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.75,
        HIT = 1.0,
        HASTE = 0.85,
        MP5 = 0.25,
    },

    WARLOCK_DPS = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 0.80,
        STAMINA = 0.55,
        SPIRIT = 0.25,
        ARMOR = 0.05,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 1.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.70,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.20,
    },

    DRUID_FERAL = {
        STRENGTH = 0.65,
        AGILITY = 1.0,
        INTELLECT = 0.15,
        STAMINA = 0.45,
        SPIRIT = 0.0,
        ARMOR = 0.25,
        ATTACKPOWER = 0.90,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 0.0,
        DODGE = 0.45,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.85,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.0,
    },

    DRUID_TANK = {
        STRENGTH = 0.40,
        AGILITY = 0.70,
        INTELLECT = 0.0,
        STAMINA = 1.0,
        SPIRIT = 0.0,
        ARMOR = 1.0,
        ATTACKPOWER = 0.35,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.0,
        HEALING = 0.0,
        DEFENSE = 0.85,
        DODGE = 1.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.20,
        HIT = 0.45,
        HASTE = 0.20,
        MP5 = 0.0,
    },

    DRUID_BALANCE = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 0.85,
        STAMINA = 0.45,
        SPIRIT = 0.45,
        ARMOR = 0.10,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 1.0,
        HEALING = 0.15,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.70,
        HIT = 1.0,
        HASTE = 0.80,
        MP5 = 0.35,
    },

    DRUID_RESTO = {
        STRENGTH = 0.0,
        AGILITY = 0.0,
        INTELLECT = 1.0,
        STAMINA = 0.45,
        SPIRIT = 0.90,
        ARMOR = 0.10,
        ATTACKPOWER = 0.0,
        RANGED_ATTACKPOWER = 0.0,
        SPELLPOWER = 0.30,
        HEALING = 1.0,
        DEFENSE = 0.0,
        DODGE = 0.0,
        PARRY = 0.0,
        BLOCK = 0.0,
        CRITICAL = 0.45,
        HIT = 0.0,
        HASTE = 0.65,
        MP5 = 0.80,
    },
}

function Weights:GetWeight(profileKey, statType)
    if not profileKey then
        return 0.0
    end

    local profileWeights = self.PROFILE_WEIGHTS[profileKey]

    if not profileWeights then
        return 0.0
    end

    local weight = profileWeights[statType] or 0.0

    if weight < 0 then
        return 0.0
    end

    if weight > 1 then
        return 1.0
    end

    return weight
end

function Weights:GetProfileWeights(profileKey)
    return self.PROFILE_WEIGHTS[profileKey] or {}
end